name: Nightly instrumented tests

on:
  workflow_call:
    inputs:
      sha:
        description: 'SHA to run against'
        required: false
        type: string
      file_issue_branch:
        description: 'Branch used in filed issues; if unset, no issues are filed'
        required: false
        type: string
      go_version:
        description: 'Go version'
        required: false
        default: '1.25'
        type: string
  workflow_dispatch:
    inputs:
      sha:
        description: 'SHA to run against'
        required: false
        type: string
      file_issue_branch:
        description: 'Branch used in filed issues; if unset, no issues are filed'
        required: false
        type: string
      go_version:
        description: 'Go version'
        required: false
        default: '1.25'
        type: string

jobs:
  linux-asan-22-04:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4
        with:
          ref: ${{ inputs.sha || github.sha }}

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: ${{ inputs.go_version }}

      - run: |
          sudo sysctl -w kernel.core_pattern='/tmp/core.%e.%p'
          ulimit -c unlimited
          for i in `seq 1 100`; do
            GOTRACEBACK=all ASAN_OPTIONS=detect_invalid_pointer_pairs=1:detect_odr_violation=1:alloc_dealloc_mismatch=1:malloc_context_size=20:detect_leaks=0 \
              go test -asan -tags 'invariants slowbuild' ./internal/cache ./internal/metamorphic -count=10
          done

      - name: Build test binaries for debugging
        if: failure()
        run: |
          go test -c -asan -tags 'invariants slowbuild' -o cache.test ./internal/cache
          go test -c -asan -tags 'invariants slowbuild' -o metamorphic.test ./internal/metamorphic

      - name: Upload crash artifacts
        if: failure()
        uses: actions/upload-artifact@v4
        with:
          name: asan-crash-artifacts
          path: |
            /tmp/core.*
            cache.test
            metamorphic.test
          if-no-files-found: ignore

      - name: Post issue on failure
        if: failure() && inputs.file_issue_branch != ''
        id: create-or-update-unique-issue
        uses: ./.github/actions/post-issue
        with:
          title: "${{ inputs.file_issue_branch }}: nightly ${{ github.job }} failed"
          body: "The nightly ${{ github.job }} test run failed on ${{ inputs.sha }} (go${{ inputs.go_version }}). Please review the run [here](${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }})."
          labels: "C-test-failure"

  linux-asan-24-04:
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v4
        with:
          ref: ${{ inputs.sha || github.sha }}

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: ${{ inputs.go_version }}

      - run: |
          sudo sysctl -w kernel.core_pattern='/tmp/core.%e.%p'
          ulimit -c unlimited
          for i in `seq 1 100`; do
            GOTRACEBACK=all ASAN_OPTIONS=detect_invalid_pointer_pairs=1:detect_odr_violation=1:alloc_dealloc_mismatch=1:malloc_context_size=20:detect_leaks=0 \
              go test -asan -tags 'invariants slowbuild' ./internal/cache ./internal/metamorphic -count=10
          done

      - name: Build test binaries for debugging
        if: failure()
        run: |
          go test -c -asan -tags 'invariants slowbuild' -o cache.test ./internal/cache
          go test -c -asan -tags 'invariants slowbuild' -o metamorphic.test ./internal/metamorphic

      - name: Upload crash artifacts
        if: failure()
        uses: actions/upload-artifact@v4
        with:
          name: asan-crash-artifacts
          path: |
            /tmp/core.*
            cache.test
            metamorphic.test
          if-no-files-found: ignore

      - name: Post issue on failure
        if: failure() && inputs.file_issue_branch != ''
        id: create-or-update-unique-issue
        uses: ./.github/actions/post-issue
        with:
          title: "${{ inputs.file_issue_branch }}: nightly ${{ github.job }} failed"
          body: "The nightly ${{ github.job }} test run failed on ${{ inputs.sha }} (go${{ inputs.go_version }}). Please review the run [here](${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }})."
          labels: "C-test-failure"
